# Generated by Django 6.0.5 on 2026-05-30 04:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_staff_base_salary_payroll_staffattendance'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='paid_by',
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AddField(
            model_name='payment',
            name='receipted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='receipted_payments', to='core.staff'),
        ),
    ]
