# Generated by Django 6.0.5 on 2026-06-01 05:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_seed_standard_chart_of_accounts'),
    ]

    operations = [
        migrations.AddField(
            model_name='staffattendance',
            name='absence_reason',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='staffattendance',
            name='replacement_staff',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='replacement_attendance_records', to='core.staff'),
        ),
    ]
