# Generated by Django 6.0.5 on 2026-06-01 06:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_staffattendance_absence_reason_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='staffattendance',
            name='auto_created_replacement',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='staffattendance',
            name='replacement_for_staff',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='covered_attendance_records', to='core.staff'),
        ),
    ]
