# Generated by Django 6.0.5 on 2026-06-01 06:30

import core.models
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auditlog_ip_address_auditlog_method_auditlog_path_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='auditlog',
            name='activity_date',
            field=models.DateField(default=django.utils.timezone.localdate),
        ),
        migrations.AddField(
            model_name='auditlog',
            name='activity_time',
            field=models.TimeField(default=core.models.current_local_time),
        ),
    ]
