# Generated by Django 6.0.5 on 2026-06-01 11:12

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


def seed_application_requirements(apps, schema_editor):
    ApplicationRequirement = apps.get_model('core', 'ApplicationRequirement')
    requirements = [
        ('Birth Certificate', 'Applicant birth certificate or national identification document.', 1),
        ('Previous School Report', 'Most recent academic report from the previous school.', 2),
        ('Passport Photo', 'Clear recent passport-size photo of the applicant.', 3),
        ('Medical Form', 'Completed learner medical information form.', 4),
        ('Parent Or Guardian Details', 'Verified parent or guardian contact details.', 5),
        ('Admission Interview', 'Interview or placement review completed by the school.', 6),
    ]
    for name, description, sort_order in requirements:
        ApplicationRequirement.objects.get_or_create(
            requirement_name=name,
            applied_class=None,
            defaults={
                'description': description,
                'is_required': True,
                'sort_order': sort_order,
                'status': 'active',
            },
        )


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_auditlog_activity_date_auditlog_activity_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApplicationRequirement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('requirement_name', models.CharField(max_length=160)),
                ('description', models.TextField(blank=True)),
                ('is_required', models.BooleanField(default=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(default='active', max_length=32)),
                ('applied_class', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.schoolclass')),
            ],
            options={
                'ordering': ('sort_order', 'requirement_name'),
                'unique_together': {('requirement_name', 'applied_class')},
            },
        ),
        migrations.CreateModel(
            name='ApplicationRequirementCheck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_satisfied', models.BooleanField(default=False)),
                ('note', models.TextField(blank=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requirement_checks', to='core.onlineapplication')),
                ('requirement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.applicationrequirement')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.staff')),
            ],
            options={
                'ordering': ('requirement__sort_order', 'requirement__requirement_name'),
                'unique_together': {('application', 'requirement')},
            },
        ),
        migrations.RunPython(seed_application_requirements, migrations.RunPython.noop),
    ]
