# Generated by Django 6.0.5 on 2026-06-01 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_applicationrequirement_applicationrequirementcheck'),
    ]

    operations = [
        migrations.AddField(
            model_name='onlineapplication',
            name='application_mode',
            field=models.CharField(choices=[('online', 'Online'), ('physical', 'Physical')], default='online', max_length=32),
        ),
    ]
